name: Tests

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.31
      - name: Install WASM binaries from aspectron.org
        run: wget -O wasm.zip https://kaspa.aspectron.org/nightly/downloads/kaspa-wasm32-sdk-2024-04-11.zip
      - name: Extract WASM binaries
        run: 7z x wasm.zip web\kaspa -o/wasm
      - name: Install Dependencies
        run: bun install
      - name: Build Kaspian
        run: bun run build
