name: Build and upload assets

on:
  release:
    types: [ published ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.31
      - name: Install WASM binaries from aspectron.org
        run: wget -O wasm.zip https://kaspa.aspectron.org/nightly/downloads/kaspa-wasm32-sdk-2024-09-13.zip
      - name: Extract WASM binaries
        run: |
          7z x wasm.zip
          mkdir ./wasm
          mv ./kaspa-wasm32-sdk/web/kaspa/* ./wasm
      - name: Install Dependencies
        run: bun install
      - name: Build Kaspian
        run: bun run build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/"
          asset_name: "unpacked-extension"
